### ISSUE TITLE
Empty client directory? docker compose fails

### ISSUE THREAD

**Issue by MarkusManas** [outgive-inc/node-express-postgres-challenge#1]
Hello,

I'm not sure if this is intended so I asked through here. I was just confused since readme states that docker compose would run no problem, but web-app fails to build due to not locating a Dockerfile.dev in client dir. If this is intended and that we are supposed to fill out the client dir ourselves (dockerfile included), then I apologize for creating an issue about it.

Thank you for your time

**Comment by outgive-inc** [comment]
Hey @MarkusManas!

Sorry about that. One other candidate who made issue #2 brought up the same thing

I had some git issues that weren't keeping track of the client folder at all. It was working on Gitlab where it was originally created and was migrated here on Github.

The client folder should be present in the repo now.
