### ISSUE TITLE
Cannot locate specified Dockerfile: Dockerfile.dev

### ISSUE THREAD

**Issue by jpvinalon** [outgive-inc/node-express-postgres-challenge#2]
Hey,

After executing `docker-compose up` I got this error saying that it cannot locate the dockerfile.

**Comment by outgive-inc** [comment]
@jpvinalon Sorry about that!

I had some git issues that weren't keeping track of the client folder at all. It was working on Gitlab where it was originally created and was migrated here on Github. 

The client folder should be present in the repo now.
